[workspace]
members = ["tests", "contracts/dex-lock", "contracts/sudt"]
resolver = "2"

[profile.release]
overflow-checks = true
opt-level = 's'
lto = true
codegen-units = 1
panic = 'abort'
strip = true
